name = "A Modpack"
author = "Phyrone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa1cfef1cfe0fef189552b8bd47d93b08246090a3f41088de1c48d11d298ca3d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
