name = "A Modpack"
author = "Phyrone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6077a89e21844b5fe97faa5b931b66025f103ab786cf9ad41be88fc9037109e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
