name = "A Modpack"
author = "Phyrone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d97e544df16b61e5ef53d74da349d5139a6065b8db7eb3f768e2f62e3408b62c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
